export interface FoodItem {
  id: string;
  name: string;
  description: string;
  category: string;
  image?: string;
  availableIn?: ("classic" | "gold" | "premium")[];
}

export const foodItems: Record<string, FoodItem[]> = {
  vorspeisen: [
    {
      id: "rote_bete_salzgurken",
      name: "Rote-Bete mit Salzgurken",
      description: "Olivenöl, frischen Kräutern",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/Neu/Rotebete mit salzgurken.jpg",
    },

    {
      id: "rote_bete_birnen",
      name: "Rote-Bete mit Birnen Meerrettich",
      description: "Olivenöl, frischem Koriander",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image:
        "/images/cateringbilder/neu3/Rotebete mit Birnen und Meerrettich.jpeg",
    },
    {
      id: "suesskartoffeln_rote_bete",
      name: "Süßkartoffeln mit Rote Bete",
      description: "Kichererbsen",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/neu3/Rotebete mit Süßkartoffeln.jpeg",
    },
    {
      id: "moehren_salat",
      name: "Möhren Salat",
      description: "Frisch und knackig",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/neu2/Mohren Salat.jpeg",
    },
    {
      id: "kus_kus_paprika",
      name: "Kus kus mit Paprika",
      description: "Gurken und frischen Kräutern",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/neu2/Cous cous mit Paprika Salat.jpeg",
    },

    {
      id: "bohnensalat",
      name: "Bohnensalat",
      description: "Bohnensalat",
      category: "Salate",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/neu3/bohnensalat.jpeg",
    },

    {
      id: "judischer_salat",
      name: "Jüdischer Salat",
      description: "Jüdischer Salat",
      category: "Salate",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/neu3/Judische Salat.jpeg",
    },

    {
      id: "Hering_unter_Rotebete_Mantel",
      name: "Hering unter Rotebete Mantel",
      description: "Hering unter Rotebete Mantel",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/neu3/Hering unter Rotebete Mantel.jpeg",
    },

    {
      id: "gefuellte_auberginen",
      name: "Gefüllte Auberginen",
      description: "Gefüllte Auberginen",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/neu3/Gefülltte Auberginen.jpeg",
    },

 {
      id: "auberginen_saute",
      name: "Auberginen Saute",
      description: "Auberginen Saute",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/neu3/Auberginen Saute.jpeg",
    },

{
      id: "fischplatte",
      name: "Fischplatte",
      description: "Fischplatte",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/neu3/Fischplatte.jpeg",
    },

    {
      id: "fleischplatte",
      name: "Fleischplatte",
      description: "Fleischplatte",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/neu3/Fleischplatte.jpeg",
    },

    {
      id: "gebackene_auberginen",
      name: "Gebackene Auberginen",
      description: "Gebackene Auberginen mit Kichererbsen, Paprika",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/neu3/Gebackene Auberginen mit Kichererbsen,  Paprika.jpeg",
    },


    {
      id: "eingelegte_gemuese",
      name: "Eingelegte Gemüse",
      description: "Eingelegte Gemüse",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/neu3/Eingelegte Gemüse.jpeg",
    },

    {
      id: "ganze_auberginen",
      name: "Ganze Auberginen",
      description: "Ganze Auberginen",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/neu3/Ganze Auberginen.jpeg",
    },

    {
      id: "nudeln_italien",
      name: "Nudeln nach Italien Art",
      description: "Getrocknete Tomaten, Oliven, Provençer Kräuter",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/Nudeln nach Italien Art.jpeg",
    },
    {
      id: "hummus",
      name: "Hummus",
      description: "Cremig und aromatisch",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/Hummus.jpeg",
    },
    {
      id: "falafel",
      name: "Knusprige Falafel",
      description: "Frisch frittiert",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/neu3/Knusprige Falafel.jpg",
    },
    {
      id: "suesskartoffeln_tahini",
      name: "Gebackene Süßkartoffeln mit Tahini",
      description: "Dattelsirup",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/neu2/Süßkartoffeln Salat mit Tahini.jpeg",
    },

    {
      id: "vinaigrette_rote_bete",
      name: "Rote-Bete mit Vinaigrette",
      description: "Olivenöl, frischem Koriander",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/Neu/Rotebete mit salzgurken.jpg",
    },

    {
      id: "kartoffeln_salat_israeli",
      name: "Kartoffeln Salat nach Israelischer Art",
      description: "Traditionell gewürzt",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image:
        "/images/cateringbilder/Kartoffeln Salat nach Israelischer Art.jpeg",
    },
    {
      id: "funcheza_salat",
      name: "Funcheza Salat",
      description: "Glasnudeln mit Paprika, Möhren, Sesam, Koriander",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/Neu/Funcheza Salat.jpg",
    },
    {
      id: "israelischer_salat",
      name: "Israelischer Salat",
      description: "Frisches Gemüse und Kräuter",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/Israelischer Salat.jpeg",
    },
    {
      id: "weisskohl_rotkohl",
      name: "Weißkohl/ Rotkohl Salat",
      description: "Mit Erbsen",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/WeißkohlRotkohl Salat mit Erbsen.jpeg",
    },
    {
      id: "matbucha",
      name: "Matbucha nach Israelischer Art",
      description: "Würzige Paprika-Tomaten-Paste",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/neu2/Matbucha.jpeg",
    },
    {
      id: "rote_bete_pflaumen",
      name: "Rote-Bete klassischer Salat",
      description: "Pflaumen, Walnuss, Mayonnaise",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/neu2/Rotebete klassischer Salat.jpeg",
    },
    {
      id: "garten_salat",
      name: "Garten Salat",
      description: "Spinat, Tomaten, Rucola",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image:
        "/images/cateringbilder/Garten Salat ( Spinat, Tomaten und Rucola).jpeg",
    },
    {
      id: "gemueseauflauf",
      name: "Gemüseauflauf",
      description: "Gemüse nach Wahl",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/neu2/Gemüse Auflauf.jpeg",
    },
    {
      id: "nudelauflauf",
      name: "Nudelauflauf",
      description: "Cremig überbacken",
      category: "Vorspeisen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/neu2/Nudelauflauf.jpeg",
    },
  ],
  fingerfoods: [
    {
      id: "blini_kartoffeln",
      name: "Blini mit Kartoffeln",
      description: "Warme Vorspeise",
      category: "Warme Vorspeisen",
      availableIn: ["gold", "premium"],
      image: "/images/cateringbilder/Neu/Blini mit Karrtoffeln.jpg",
    },
    {
      id: "blini_haehnchen",
      name: "Blini mit Hähnchenfleisch",
      description: "Warme Vorspeise",
      category: "Warme Vorspeisen",
      availableIn: ["gold", "premium"],
      image: "/images/cateringbilder/Neu/Blini mit Karrtoffeln.jpg",
    },
    {
      id: "blini_pilze",
      name: "Blini mit Pilzen",
      description: "Warme Vorspeise",
      category: "Warme Vorspeisen",
      availableIn: ["gold", "premium"],
      image: "/images/cateringbilder/Neu/Blini mit Karrtoffeln.jpg",
    },
    {
      id: "burekas_kartoffeln",
      name: "Burekas mit Kartoffeln",
      description: "Warme Vorspeise",
      category: "Warme Vorspeisen",
      availableIn: ["gold", "premium"],
      image: "/images/dishes/bourekas.jpg",
    },
  ],
  suppen: [
    {
      id: "kartoffel_cremesuppe",
      name: "Kartoffel Cremesuppe",
      description: "Cremig und herzhaft",
      category: "Suppen",
      availableIn: ["premium"],
      image: "/images/cateringbilder/neu3/Kartoffeln Suppe.jpeg",
    },
    {
      id: "gemuesesuppe",
      name: "Gemüsesuppe",
      description: "Frisch und gesund",
      category: "Suppen",
      availableIn: ["premium"],
      image: "/images/dishes/borscht.jpg",
    },
    {
      id: "vegetarisch_nudeln_suppe",
      name: "Vegetarische Nudelsuppe",
      description: "Leicht und wohltuend",
      category: "Suppen",
      availableIn: ["premium"],
      image: "/images/cateringbilder/neu3/Vegetarische Nudel suppe.jpeg",
    },
    {
      id: "borschtsch",
      name: "Borschtsch",
      description: "Traditionelle Rote-Bete-Suppe",
      category: "Suppen",
      availableIn: ["premium"],
      image: "/images/cateringbilder/neu3/Bortsch.jpeg",
    },
    {
      id: "haehnchen_nudeln_suppe",
      name: "Hähnchen Nudelsuppe",
      description: "Kräftigend und lecker",
      category: "Suppen",
      availableIn: ["premium"],
      image: "/images/cateringbilder/neu3/nudelsuppe.jpeg",
    },
  ],
  hauptgaenge: [
    {
      id: "lachs_cocos_limette",
      name: "Lachsfiletstücke in Kokos-Limetten-Sauce",
      description: "Exotisch und aromatisch",
      category: "Fischgerichte",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/lachsfilet im cocos limette sauce.jpg",
    },
    {
      id: "dorade_paprika_wein",
      name: "Dorade in Paprika-Weinsauce",
      description: "Mediterran gewürzt",
      category: "Fischgerichte",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/neu2/Dorade im Paprika weinsauce.jpeg",
    },
    {
      id: "zander_tomaten",
      name: "Gebackenes Zanderfilet in Tomatensauce",
      description: "Nach israelischer Art",
      category: "Fischgerichte",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/neu2/Zanderfilet in Tomaten Sauce.jpeg",
    },
    {
      id: "haehnchenschenkel_tomaten",
      name: "Hähnchenschenkel in Tomatensauce",
      description: "Saftig und würzig",
      category: "Geflügelgerichte",
      availableIn: ["classic", "gold", "premium"],
      image:
        "/images/cateringbilder/neu2/Gebackene hahnchenkeule im Tomaten Sauce.jpeg",
    },
    {
      id: "pargiot",
      name: "Pargiot",
      description: "Israelische Hähnchenspezialität",
      category: "Geflügelgerichte",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/neu2/Pargiot.jpeg",
    },
    {
      id: "geschnitzeltes_haehnchen_pute",
      name: "Hähnchen/Puten Geschnetzeltes",
      description: "In Kokos-Zitronen-Vinaigrette",
      category: "Geflügelgerichte",
      availableIn: ["classic", "gold", "premium"],
      image:
        "/images/cateringbilder/neu2/Hahnchengeschnitzeltes in kokos zitronen vinegrete.jpeg",
    },
    {
      id: "puten_schnitzel",
      name: "Puten Schnitzel",
      description: "Knusprig paniert",
      category: "Geflügelgerichte",
      availableIn: ["gold", "premium"],
      image: "/images/cateringbilder/neu3/puten.jpeg",
    },
    {
      id: "haehnchen_fluegel",
      name: "Hähnchen Flügel",
      description: "Würzig mariniert",
      category: "Geflügelgerichte",
      availableIn: ["gold", "premium"],
      image: "/images/cateringbilder/neu3/Hähnchen Flügel.jpeg",
    },
    {
      id: "rindergulasch",
      name: "Rindergulasch",
      description: "Traditionell geschmort",
      category: "Rindfleischgerichte",
      availableIn: ["gold", "premium"],
      image: "/images/cateringbilder/neu3/rindergu.jpeg",
    },
    {
      id: "boeuf_stroganoff",
      name: "Bœuf Stroganoff",
      description: "Klassisch russisch",
      category: "Rindfleischgerichte",
      availableIn: ["gold", "premium"],
      image: "/images/cateringbilder/neu3/Beffstroganov.jpeg",
    },
    {
      id: "rinderbraten",
      name: "Rinderbraten",
      description: "Saftig und aromatisch",
      category: "Rindfleischgerichte",
      availableIn: ["gold", "premium"],
      image: "/images/cateringbilder/neu3/Rinderbraten.jpeg",
    },
    {
      id: "rinderballchen_frikadellen",
      name: "Rinderbällchen/Frikadellen in Tomatensauce",
      description: "Herzhaft und lecker",
      category: "Rindfleischgerichte",
      availableIn: ["gold", "premium"],
      image: "/images/cateringbilder/neu3/Rinderbällchen.jpeg",
    },
    {
      id: "plov_usbekisch",
      name: "Plov nach Usbekischer Art",
      description: "Traditionelles Reisgericht",
      category: "Rindfleischgerichte",
      availableIn: ["gold", "premium"],
      image: "/images/cateringbilder/plov.jpg",
    },
    {
      id: "bolognese",
      name: "Bolognese",
      description: "Italienische Fleischsauce",
      category: "Rindfleischgerichte",
      availableIn: ["gold", "premium"],
      image: "/images/cateringbilder/Fleischplatte.jpeg",
    },
  ],
  beilagen: [
    {
      id: "gemuesereis",
      name: "Gemüsereis",
      description: "Bunt und gesund",
      category: "Beilagen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/neu2/Gemüse reis.jpeg",
    },
    {
      id: "gebackene_kartoffeln",
      name: "Gebackene Kartoffeln",
      description: "Knusprig aus dem Ofen",
      category: "Beilagen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/neu2/Gebackene Kartoffeln.jpeg",
    },
    {
      id: "gelber_reis",
      name: "Gelber Reis",
      description: "Aromatisch gewürzt",
      category: "Beilagen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/neu2/Gelbereis.jpeg",
    },
    {
      id: "nudeln",
      name: "Nudeln",
      description: "Al dente gekocht",
      category: "Beilagen",
      availableIn: ["classic", "gold", "premium"],
      image: "/images/cateringbilder/neu2/Nudel als Beilage.jpeg",
    },
    {
      id: "drillinge",
      name: "Drillinge Salzkartoffeln",
      description: "Kleine Kartoffeln",
      category: "Beilagen",
      availableIn: ["gold", "premium"],
      image: "/images/cateringbilder/neu3/Beilage Drillinge.jpeg",
    },
    {
      id: "gemuese_saisonal",
      name: "Gemüse",
      description: "Saisonales Gemüse",
      category: "Beilagen",
      availableIn: ["gold", "premium"],
      image: "/images/cateringbilder/neu3/Gemüse Beilage1.jpeg",
    },
  ],
  dips_saucen: [],
  desserts: [
    {
      id: "saison_obst",
      name: "Saison Obst",
      description: "Frische Früchte der Saison",
      category: "Dessert",
      availableIn: ["gold", "premium"],
      image: "/images/cateringbilder/Obstplatte.jpeg",
    },
    {
      id: "gebaeck",
      name: "Gebäck nach Absprache",
      description: "Verschiedene hausgemachte Süßspeisen",
      category: "Dessert",
      availableIn: ["premium"],
      image: "/images/dishes/torte.jpg",
    },
  ],
};

export function getPackageItems(
  packageName: "classic" | "gold" | "premium",
): Record<string, number> {
  const limits = {
    classic: {
      // Menü 1: 4 Salate + 2 Vorspeisen, 2 Hauptspeisen (1 Fisch + 1 Geflügel), 4 Beilagen
      vorspeisen: 6,
      hauptgaenge: 2,
      fingerfoods: 0,
      beilagen: 4,
      dips_saucen: 0,
      desserts: 0,
      suppen: 0,
    },
    gold: {
      // Menü 2: 5 Salate + 2 Vorspeisen, 1 warme Vorspeise, 2 Hauptspeisen, 5 Beilagen, 1 Dessert - ab 25 Personen
      vorspeisen: 7,
      hauptgaenge: 2,
      fingerfoods: 1,
      beilagen: 5,
      dips_saucen: 0,
      desserts: 1,
      suppen: 0,
    },
    premium: {
      // Menü 3: 6 Salate + 2 Vorspeisen, 1 warme Vorspeise, 1 Suppe, 3 Hauptspeisen, 3 Beilagen, 2 Desserts - ab 30 Personen
      vorspeisen: 8,
      hauptgaenge: 3,
      fingerfoods: 1,
      beilagen: 3,
      dips_saucen: 0,
      desserts: 2,
      suppen: 1,
    },
  };

  return limits[packageName];
}
