export interface FoodItem {
  id: string;
  name: string;
  description: string;
  category: string;
  price?: number;
  image?: string;
}

export const foodItems: Record<string, FoodItem[]> = {
  vorspeisen: [
    {
      id: "kaeseplatte",
      name: "Käseplatte",
      description: "Verschiedene Käsesorten, Oliven",
      category: "Vorspeisen",
      price: 15.9,
      image: "/images/dishes/kaeseplatte.jpg",
    },
    {
      id: "fleischteller",
      name: "Fleischteller",
      description:
        "Rinderzunge, Hähnchenrouladen mit Pflaumen, hausgemachte Hähnchenwurst mit Champignons",
      category: "Vorspeisen",
      price: 24.5,
      image: "/images/dishes/fleischteller.jpg",
    },
    {
      id: "fischteller",
      name: "Fischteller",
      description: "Lachs, Hering mit Kartoffeln, Kaviar Kanapees",
      category: "Vorspeisen",
      price: 29.5,
      image: "/images/dishes/fischteller.jpg",
    },
    {
      id: "eingelegtes_gemuese",
      name: "Eingelegtes Gemüse",
      description: "Hauseingelegte Gurken, Tomaten, Weisskohl, Möhren",
      category: "Vorspeisen",
      price: 16.5,
      image: "/images/dishes/eingelegtes-gemuese.jpg",
    },
    {
      id: "hering_kartoffeln",
      name: "Hering mit gekochten Kartoffeln",
      description: "Traditioneller Klassiker",
      category: "Vorspeisen",
      price: 9.5,
      image: "/images/dishes/hering-kartoffeln.jpg",
    },
    {
      id: "pilzvariationen",
      name: "Pilzvariationen",
      description: "Aus hauseingelegten Pilzen",
      category: "Vorspeisen",
      price: 12.5,
      image: "/images/dishes/pilzvariationen.jpg",
    },
    {
      id: "gebackene_auberginen",
      name: "Gebackene Auberginen",
      description: "Mit Tomaten, Zitrone, Kräuter",
      category: "Vorspeisen",
      price: 11.5,
      image: "/images/dishes/auberginen.jpg",
    },
    {
      id: "shemesh_vorspeisen_teller",
      name: "Shemesh Vorspeisen Teller (2 Per.)",
      description:
        "Fisch, Fleisch, Eingelegtes Gemüse, Auberginen, Jüdischer Salat, Hummus",
      category: "Vorspeisen",
      price: 25.9,
      image: "/images/dishes/vorspeisen-teller.jpg",
    },
    {
      id: "hummus",
      name: "Hummus",
      description: "Gebratene Kichererbsen, Pimentos, Tahini",
      category: "Vorspeisen",
      price: 10.9,
      image: "/images/dishes/hummus.jpg",
    },
    {
      id: "babaganoush",
      name: "Babaganoush",
      description:
        "Gebratene Auberginen gefüllt mit Walnüssen, Granatapfelsauce, Kräuter",
      category: "Vorspeisen",
      price: 13.5,
      image: "/images/dishes/babaganoush.jpg",
    },
    {
      id: "jud_salat",
      name: "Jüdischer Salat",
      description: "Traditionelles Gericht",
      category: "Vorspeisen",
      price: 16.5,
      image: "/images/dishes/juedischer-salat.jpg",
    },
    {
      id: "shemesh_salat",
      name: "SHEMESH Salat",
      description: "Tomaten, Gurken, Kräuter, Zwiebeln, Oliven, Schafskäse",
      category: "Vorspeisen",
      price: 12.9,
      image: "/images/dishes/shemesh-salat.jpg",
    },
    {
      id: "shemesh_vorspeisen_menu",
      name: "Shemesh Vorspeisen menü (5 Per.)",
      description:
        "Fischplatte, Fleischplatte, Eingelegtes Gemüse, Auberginen, Jüdischer Salat, Hummus",
      category: "Vorspeisen",
      price: 110.0,
      image: "/images/dishes/vorspeisen-menu.jpg",
    },
  ],
  fingerfoods: [
    {
      id: "shemesh_blinis",
      name: "Shemesh Blinis",
      description: "Pfannkuchen mit rotem Kaviar",
      category: "Zwischengerichte",
      price: 16.5,
      image: "/images/dishes/blinis-kaviar.jpg",
    },
    {
      id: "blinis_fleisch",
      name: "Blinis mit Fleisch",
      description: "Pfannkuchen mit Hühnerfleisch",
      category: "Zwischengerichte",
      price: 12.5,
      image: "/images/dishes/blinis-fleisch.jpg",
    },
    {
      id: "tschebureki",
      name: "Tschebureki",
      description: "Hausgemachte Teigtaschen mit Hackfleisch",
      category: "Zwischengerichte",
      price: 12.5,
      image: "/images/dishes/tschebureki.jpg",
    },
    {
      id: "bourekas",
      name: "Bourekas nach Israel Style",
      description: "Hausgemachte Teigtaschen mit Schafskäse-Kräuter Füllung",
      category: "Zwischengerichte",
      price: 12.5,
      image: "/images/dishes/bourekas.jpg",
    },
    {
      id: "wareniki_kartoffeln",
      name: "Wareniki mit Kartoffeln",
      description: "Hausgemachte Teigtaschen mit Kartoffeln",
      category: "Zwischengerichte",
      price: 13.9,
      image: "/images/dishes/wareniki-kartoffeln.jpg",
    },
    {
      id: "manty",
      name: "Manty",
      description:
        "Hausgemachte gedämpfte Teigtaschen mit Rindfleischfüllung, Zwiebeln",
      category: "Zwischengerichte",
      price: 17.9,
      image: "/images/dishes/manty.jpg",
    },
    {
      id: "pelmeni",
      name: "Pelmeni",
      description: "Hausgemachte Teigtaschen mit Hackfleisch",
      category: "Zwischengerichte",
      price: 15.9,
      image: "/images/dishes/pelmeni.jpg",
    },
    {
      id: "hinkali",
      name: "Hinkali Georgien Art",
      description: "Hinkali mit saftigem Hackfleisch",
      category: "Zwischengerichte",
      price: 17.9,
      image: "/images/dishes/hinkali.jpg",
    },
  ],
  suppen: [
    {
      id: "fischsuppe",
      name: "Fischsuppe",
      description: "Klassische Fischsuppe",
      category: "Suppe",
      price: 16.9,
      image: "/images/dishes/fischsuppe.jpg",
    },
    {
      id: "borscht",
      name: "Borscht",
      description: "Vegetarische Suppe aus Rote Beete und Kohl",
      category: "Suppe",
      price: 9.9,
      image: "/images/dishes/borscht.jpg",
    },
  ],
  hauptgaenge: [
    {
      id: "junges_huhn_tabaka",
      name: "Junges Huhn Tabaka",
      description: "Ofenkartoffeln, Adzhika",
      category: "Fleischgerichte",
      price: 19.5,
      image: "/images/dishes/huhn-tabaka.jpg",
    },
    {
      id: "kalbsbaeckchen",
      name: "Geschmorte Kalbsbäckchen vom Galloway",
      description: "Auberginen-Mousse, Jus",
      category: "Fleischgerichte",
      price: 28.9,
      image: "/images/dishes/kalbsbaeckchen.jpg",
    },
    {
      id: "lamm_haxe",
      name: "Lamm Haxe",
      description: "Kartoffelpüree, Jus",
      category: "Fleischgerichte",
      price: 28.9,
      image: "/images/dishes/lamm-haxe.jpg",
    },
    {
      id: "kievskaja_kotleta",
      name: "Kievskaja Kotleta",
      description: "Hähnchenfilet, Butterfüllung, Kartoffelpüree",
      category: "Fleischgerichte",
      price: 21.9,
      image: "/images/dishes/kievskaja-kotleta.jpg",
    },
    {
      id: "sabich_jerusalem",
      name: "Sabich Jerusalem Art (Vegetarisch)",
      description: "Hummus, Auberginen, Kartoffeln, Israelischer Salat",
      category: "Fleischgerichte",
      price: 16.9,
      image: "/images/dishes/sabich.jpg",
    },
    {
      id: "lachsfilet",
      name: "Lachsfilet",
      description: "Kartoffelpüree, Gemüse-Ratatouille",
      category: "Fischgerichte",
      price: 25.9,
      image: "/images/dishes/lachsfilet.jpg",
    },
    {
      id: "zanderfilet",
      name: "Zanderfilet",
      description: "Kartoffelpüree, Gemüse",
      category: "Fischgerichte",
      price: 26.9,
      image: "/images/dishes/zanderfilet.jpg",
    },
    {
      id: "stoerfisch",
      name: "Störfisch am Spieß gegrillt auf Holzkohle",
      description: "Kartoffeln, Gemüse",
      category: "Fischgerichte",
      price: 35.9,
      image: "/images/dishes/stoerfisch.jpg",
    },
    {
      id: "fischvariationen",
      name: "Fischvariationen 3 Personen",
      description:
        "Verschiedene Fischvariationen: Störspieß, Lachs, Zander, Garnelen, Gemüse, Kartoffeln aus dem Ofen",
      category: "Fischgerichte",
      price: 110.0,
      image: "/images/dishes/fischvariationen.jpg",
    },
    {
      id: "garnelen_oel",
      name: "Garnelen in Öl",
      description: "Köstliche Garnelenvariante",
      category: "Fischgerichte",
      price: 19.9,
      image: "/images/dishes/garnelen.jpg",
    },
    {
      id: "gegrillter_pulpo",
      name: "Gegrillter Pulpo",
      description: "Kartoffelpüree, Chimichurri",
      category: "Fischgerichte",
      price: 19.9,
      image: "/images/dishes/pulpo.jpg",
    },
    {
      id: "pargiot",
      name: "Pargiot",
      description: "Ausgelöste Hähnchenkeule, Gemüse, Kartoffeln, Jus",
      category: "Grill",
      price: 19.5,
      image: "/images/dishes/pargiot.jpg",
    },
    {
      id: "rinderhackspiess",
      name: "Rinderhackspieß",
      description: "Gemüse, Ofenkartoffeln",
      category: "Grill",
      price: 19.9,
      image: "/images/dishes/rinderhackspiess.jpg",
    },
    {
      id: "haehnchenspiess",
      name: "Hähnchenspieß",
      description: "Gemüse, Kartoffeln",
      category: "Grill",
      price: 19.5,
      image: "/images/dishes/haehnchenspiess.jpg",
    },
    {
      id: "lammspiess",
      name: "Lammspieß",
      description: "Gemüse, Ofenkartoffeln",
      category: "Grill",
      price: 23.5,
      image: "/images/dishes/lammspiess.jpg",
    },
    {
      id: "lammkarree",
      name: "Lammkarree",
      description: "Gemüse, Ofenkartoffeln",
      category: "Grill",
      price: 36.5,
      image: "/images/dishes/lammkarree.jpg",
    },
    {
      id: "jerusalem_grillplatte",
      name: "Jerusalem-Grillplatte (3 Per.)",
      description:
        "Lammspieß, Rinderhackspieß, Hähnchenspieß, Gemüse, Kartoffeln",
      category: "Grill",
      price: 65.0,
      image: "/images/dishes/grillplatte.jpg",
    },
    {
      id: "ribeye_steak",
      name: "Ribeye - Steak",
      description: "Rosmarinkartoffeln, Jus",
      category: "Grill",
      price: 31.9,
      image: "/images/dishes/ribeye.jpg",
    },
  ],
  beilagen: [],
  dips_saucen: [],
  desserts: [
    {
      id: "blini_eis",
      name: "Blini mit Eis",
      description: "Süße Pfannkuchen mit Vanilleeis",
      category: "Dessert",
      price: 9.5,
      image: "/images/dishes/blini-eis.jpg",
    },
    {
      id: "shemesh_tortenauswahl",
      name: "Hausgebackene SHEMESH Tortenauswahl",
      description: "Vielfältige Auswahl an frisch gebackenen Torten",
      category: "Dessert",
      price: 9.5,
      image: "/images/dishes/torte.jpg",
    },
    {
      id: "blini_marmelade",
      name: "Blinis mit Marmelade",
      description: "Mit hausgemachter Marmelade",
      category: "Dessert",
      price: 9.5,
      image: "/images/dishes/blini-marmelade.jpg",
    },
    {
      id: "wareniki_kirschen",
      name: "Wareniki mit Kirschen",
      description: "Süßer Schmand",
      category: "Dessert",
      price: 13.5,
      image: "/images/dishes/wareniki-kirschen.jpg",
    },
    {
      id: "suesse_birne",
      name: "Süße Birne mit Eis",
      description: "Köstliche Birnenvariante",
      category: "Dessert",
      price: 9.5,
      image: "/images/dishes/birne-eis.jpg",
    },
  ],
};

export function getPackageItems(
  packageName: "classic" | "gold" | "premium"
): Record<string, number> {
  const limits = {
    classic: {
      vorspeisen: 2,
      hauptgaenge: 2,
      fingerfoods: 2,
      beilagen: 0,
      dips_saucen: 0,
      desserts: 1,
      suppen: 1,
    },
    gold: {
      vorspeisen: 3,
      hauptgaenge: 3,
      fingerfoods: 3,
      beilagen: 0,
      dips_saucen: 0,
      desserts: 2,
      suppen: 1,
    },
    premium: {
      vorspeisen: 4,
      hauptgaenge: 3,
      fingerfoods: 3,
      beilagen: 0,
      dips_saucen: 0,
      desserts: 3,
      suppen: 2,
    },
  };

  return limits[packageName];
}
