export interface FoodItem {
  id: string
  name: string
  description: string
  category: string
  price?: number
}

export const foodItems: Record<string, FoodItem[]> = {
  vorspeisen: [
    {
      id: "coleslaw",
      name: "Coleslaw",
      description: "Coleslaw, verfeinert mit einem delikaten Dressing aus hochwertigen Zutaten.",
      category: "Vorspeisen",
    },
    {
      id: "kartoffelsalat",
      name: "Kartoffelsalat",
      description: "Gekochte Kartoffeln in einer würzigen, cremigen Soße, abgerundet mit frischen Kräutern.",
      category: "Vorspeisen",
    },
    {
      id: "kisir",
      name: "Kisir",
      description: "Kisir, einen erfrischenden Bulgur-Salat, verfeinert mit aromatischen mediterranen Gewürzen.",
      category: "Vorspeisen",
    },
    {
      id: "nudelsalat",
      name: "Nudelsalat",
      description: "Nudelsalat mit knackigem Gemüse, Eiern und einem unwiderstehlichen Dressing!",
      category: "Vorspeisen",
    },
    {
      id: "brokkoli_salat",
      name: "Brokkoli Salat",
      description: "Frischer Brokkoli trifft auf cremiges Dressing, geröstete Nüsse und feine Extras.",
      category: "Vorspeisen",
    },
    {
      id: "gruener_salat",
      name: "Grüner Salat",
      description:
        "Frischer, knackiger Blattsalat vereint mit Walnüssen, saftigen Granatapfelkernen und zartem Schafskäse.",
      category: "Vorspeisen",
    },
    {
      id: "gurkensalat",
      name: "Gurkensalat",
      description: "Erfrischender Gurkensalat mit knackigen Gurken, verfeinert mit einer leichten Vinaigrette.",
      category: "Vorspeisen",
    },
    {
      id: "bauersalat",
      name: "Bauernsalat (Coban Salatasi)",
      description: "Frischer Bauernsalat vereint knackige Gurken, reife Tomaten, rote Zwiebeln und Paprika.",
      category: "Vorspeisen",
    },
    {
      id: "kaeseplatte",
      name: "Käseplatte",
      description: "Verschiedene Käsesorten mit Oliven",
      category: "Vorspeisen",
      price: 15.9,
    },
    {
      id: "fleischteller",
      name: "Fleischteller",
      description: "Rinderzunge, Hähnchenrouladen mit Pflaumen, hausgemachte Hähnchenwurst mit Champignons",
      category: "Vorspeisen",
      price: 24.5,
    },
    {
      id: "fischteller",
      name: "Fischteller",
      description: "Lachs, Hering mit Kartoffeln, Kaviar Kanapees",
      category: "Vorspeisen",
      price: 29.5,
    },
    {
      id: "eingelegtes_gemuese",
      name: "Eingelegtes Gemüse",
      description: "Hauseingelegte Gurken, Tomaten, Weisskohl, Möhren",
      category: "Vorspeisen",
      price: 16.5,
    },
    {
      id: "hering_kartoffeln",
      name: "Hering mit gekochten Kartoffeln",
      description: "Traditioneller Klassiker",
      category: "Vorspeisen",
      price: 9.5,
    },
    {
      id: "pilzvariationen",
      name: "Pilzvariationen",
      description: "Aus hauseingelegten Pilzen",
      category: "Vorspeisen",
      price: 12.5,
    },
    {
      id: "gebackene_auberginen",
      name: "Gebackene Auberginen",
      description: "Mit Tomaten, Zitrone und Kräutern",
      category: "Vorspeisen",
      price: 11.5,
    },
    {
      id: "hummus",
      name: "Hummus",
      description: "Gebratene Kichererbsen, Pimentos, Tahini",
      category: "Vorspeisen",
      price: 10.9,
    },
    {
      id: "babaganoush",
      name: "Babaganoush",
      description: "Gebratene Auberginen gefüllt mit Walnüssen, Granatapfelsauce, Kräuter",
      category: "Vorspeisen",
      price: 13.5,
    },
    {
      id: "jud_salat",
      name: "Jüdischer Salat",
      description: "Traditionelles Gericht",
      category: "Vorspeisen",
      price: 16.5,
    },
    {
      id: "shemesh_salat",
      name: "Shemesh Salat",
      description: "Tomaten, Gurken, Kräuter, Zwiebeln, Oliven, Schafskäse",
      category: "Vorspeisen",
      price: 12.9,
    },
    {
      id: "shemesh_vorspeisen_teller",
      name: "Shemesh Vorspeisen Teller (2 Per.)",
      description: "Fisch, Fleisch, Eingelegtes Gemüse, Auberginen, Jüdischer Salat, Hummus",
      category: "Vorspeisen",
      price: 25.9,
    },
  ],
  hauptgaenge: [
    {
      id: "hahnchenschnitzel",
      name: "Paniertes Hähnchenschnitzel",
      description: "Goldbraun paniert, außen schön knusprig und innen saftig – unser Hähnchenschnitzel.",
      category: "Hauptgänge",
    },
    {
      id: "manti",
      name: "Mantı",
      description: "Türkische Tortellini mit Hackfleischfüllung, Knoblauch-Joghurt & Butter-Tomaten-Soße.",
      category: "Hauptgänge",
    },
    {
      id: "lasagne",
      name: "Lasagne",
      description: "Genießen Sie unsere klassische Lasagne: zarte Nudelblätter, geschichtet mit würziger Bolognese.",
      category: "Hauptgänge",
    },
    {
      id: "hahnchen_champignon",
      name: "Hähnchen in Champignon Rahm Soße",
      description: "Zartes Hähnchenfilet, geschnetzelt, in einer cremigen Champignon-Rahm-Soße.",
      category: "Hauptgänge",
    },
    {
      id: "chicken_curry",
      name: "Chicken in Curry-Rahm Soße",
      description: "Zartes Hähnchenfleisch, geschnetzelt, in einer aromatischen, cremigen Currysauce.",
      category: "Hauptgänge",
    },
    {
      id: "pasta_napoli_chicken",
      name: "Pasta Napoli Chicken",
      description: "Genießen Sie unsere zarte Pasta Napoli Chicken – saftige Hähnchenstücke in Tomatensauce.",
      category: "Hauptgänge",
    },
    {
      id: "taze_fasulye",
      name: "Taze Fasulye",
      description: "Zarte grüne Bohnen, langsam geschmort in einer aromatischen Tomatensauce. (Vegetarisch)",
      category: "Hauptgänge",
    },
    {
      id: "gemuese_lasagne",
      name: "Gemüse Lasagne",
      description: "Unsere köstliche Gemüse Lasagne, geschichtet mit zarten Nudelblättern und frischem Gemüse.",
      category: "Hauptgänge",
    },
    {
      id: "pasta_napoli",
      name: "Pasta Napoli",
      description: "Genieße unsere Pasta Napoli: Frische, al dente Nudeln vereinen sich mit aromatischer Tomatensauce.",
      category: "Hauptgänge",
    },
    {
      id: "hahnchenbrust_filet",
      name: "Hähnchenbrust Filet",
      description: "Zarte Hähnchenbrustfilets, saftig gegrillt und verfeinert mit aromatischer Kräuterbutter.",
      category: "Hauptgänge",
    },
    {
      id: "kofte",
      name: "Köfte vom Grill",
      description: "Saftige, gegrillte Köfte, zubereitet aus fein gewürztem Hackfleisch. Serviert mit Fladenbrot.",
      category: "Hauptgänge",
    },
    {
      id: "junges_huhn_tabaka",
      name: "Junges Huhn Tabaka",
      description: "Ofenkartoffeln, Adzhika",
      category: "Hauptgänge",
      price: 19.5,
    },
    {
      id: "kalbsbaeckchen",
      name: "Geschmorte Kalbsbäckchen vom Galloway",
      description: "Auberginen-Mousse, Jus",
      category: "Hauptgänge",
      price: 28.9,
    },
    {
      id: "lamm_haxe",
      name: "Lamm Haxe",
      description: "Kartoffelpüree, Jus",
      category: "Hauptgänge",
      price: 28.9,
    },
    {
      id: "kievskaja_kotleta",
      name: "Kievskaja Kotleta",
      description: "Hähnchenfilet mit Butterfüllung, Kartoffelpüree",
      category: "Hauptgänge",
      price: 21.9,
    },
    {
      id: "sabich_jerusalem",
      name: "Sabich Jerusalem Art",
      description: "Hummus, Auberginen, Kartoffeln, Israelischer Salat (Vegetarisch)",
      category: "Hauptgänge",
      price: 16.9,
    },
    {
      id: "lachsfilet",
      name: "Lachsfilet",
      description: "Kartoffelpüree, Gemüse-Ratatouille",
      category: "Hauptgänge",
      price: 25.9,
    },
    {
      id: "zanderfilet",
      name: "Zanderfilet",
      description: "Kartoffelpüree, Gemüse",
      category: "Hauptgänge",
      price: 26.9,
    },
    {
      id: "stoerfisch",
      name: "Störfisch am Spieß gegrillt",
      description: "Gegrillt auf Holzkohle, Kartoffeln, Gemüse",
      category: "Hauptgänge",
      price: 35.9,
    },
    {
      id: "garnelen_oel",
      name: "Garnelen in Öl",
      description: "Köstliche Garnelenvariante",
      category: "Hauptgänge",
      price: 19.9,
    },
    {
      id: "gegrillter_pulpo",
      name: "Gegrillter Pulpo",
      description: "Kartoffelpüree, Chimichurri",
      category: "Hauptgänge",
      price: 19.9,
    },
    {
      id: "pargiot",
      name: "Pargiot",
      description: "Ausgelöste Hähnchenkeule, Gemüse, Kartoffeln, Jus",
      category: "Hauptgänge",
      price: 19.5,
    },
    {
      id: "rinderhackspiess",
      name: "Rinderhackspieß",
      description: "Gemüse, Ofenkartoffeln",
      category: "Hauptgänge",
      price: 19.9,
    },
    {
      id: "haehnchenspiess",
      name: "Hähnchenspieß",
      description: "Gemüse, Kartoffeln",
      category: "Hauptgänge",
      price: 19.5,
    },
    {
      id: "lammspiess",
      name: "Lammspieß",
      description: "Gemüse, Ofenkartoffeln",
      category: "Hauptgänge",
      price: 23.5,
    },
    {
      id: "lammkarree",
      name: "Lammkarree",
      description: "Gemüse, Ofenkartoffeln",
      category: "Hauptgänge",
      price: 36.5,
    },
    {
      id: "ribeye_steak",
      name: "Ribeye - Steak",
      description: "Rosmarinkartoffeln, Jus",
      category: "Hauptgänge",
      price: 31.9,
    },
  ],
  fingerfoods: [
    {
      id: "spring_rolls",
      name: "Frühlingsrollen",
      description: "Knusprige Frühlingsrollen mit frischem Gemüse und aromatischen Gewürzen.",
      category: "Fingerfoods",
    },
    {
      id: "mozzarella_sticks",
      name: "Mozzarella Sticks",
      description: "Goldbraun frittierte Mozzarella Sticks mit cremigem Kern.",
      category: "Fingerfoods",
    },
    {
      id: "falafel",
      name: "Falafel",
      description: "Knusprige Falafel aus feinen Kichererbsen und Gewürzen.",
      category: "Fingerfoods",
    },
    {
      id: "samosas",
      name: "Samosas",
      description: "Knusprige Samosas mit würziger Füllung.",
      category: "Fingerfoods",
    },
    {
      id: "shemesh_blinis",
      name: "Shemesh Blinis",
      description: "Pfannkuchen mit rotem Kaviar",
      category: "Fingerfoods",
      price: 16.5,
    },
    {
      id: "blinis_fleisch",
      name: "Blinis mit Fleisch",
      description: "Pfannkuchen mit Hühnerfleisch",
      category: "Fingerfoods",
      price: 12.5,
    },
    {
      id: "tschebureki",
      name: "Tschebureki",
      description: "Hausgemachte Teigtaschen mit Hackfleisch",
      category: "Fingerfoods",
      price: 12.5,
    },
    {
      id: "bourekas",
      name: "Bourekas nach Israel Style",
      description: "Hausgemachte Teigtaschen mit Schafskäse-Kräuter Füllung",
      category: "Fingerfoods",
      price: 12.5,
    },
    {
      id: "wareniki_kartoffeln",
      name: "Wareniki mit Kartoffeln",
      description: "Hausgemachte Teigtaschen mit Kartoffeln",
      category: "Fingerfoods",
      price: 13.9,
    },
    {
      id: "manty",
      name: "Manty",
      description: "Hausgemachte gedämpfte Teigtaschen mit Rindfleischfüllung, Zwiebeln",
      category: "Fingerfoods",
      price: 17.9,
    },
    {
      id: "pelmeni",
      name: "Pelmeni",
      description: "Hausgemachte Teigtaschen mit Hackfleisch",
      category: "Fingerfoods",
      price: 15.9,
    },
    {
      id: "hinkali",
      name: "Hinkali Georgien Art",
      description: "Hinkali mit saftigem Hackfleisch",
      category: "Fingerfoods",
      price: 17.9,
    },
  ],
  beilagen: [
    {
      id: "pommes",
      name: "Pommes Frites",
      description: "Knusprige, goldbraune Pommes Frites, frisch zubereitet.",
      category: "Beilagen",
    },
    {
      id: "reis",
      name: "Jasmin Reis",
      description: "Fluffy Jasmin Reis, perfekt als Beilage zu jedem Gericht.",
      category: "Beilagen",
    },
    {
      id: "gemuese",
      name: "Grillgemüse",
      description: "Frisches, gegrilltes Gemüse: Paprika, Zucchini, Aubergine und mehr.",
      category: "Beilagen",
    },
    {
      id: "ofenkartoffeln",
      name: "Ofenkartoffeln",
      description: "Frisch aus dem Ofen",
      category: "Beilagen",
      price: 4.5,
    },
    {
      id: "kartoffelpueree",
      name: "Kartoffelpüree",
      description: "Cremig und köstlich",
      category: "Beilagen",
      price: 5.0,
    },
    {
      id: "rosmarinkartoffeln",
      name: "Rosmarinkartoffeln",
      description: "Mit aromatischem Rosmarin",
      category: "Beilagen",
      price: 5.5,
    },
    {
      id: "grillgemuese",
      name: "Grillgemüse",
      description: "Paprika, Zucchini, Aubergine",
      category: "Beilagen",
      price: 6.0,
    },
  ],
  dips_saucen: [
    {
      id: "joghurt_dip",
      name: "Joghurt Dip",
      description: "Cremiger Joghurt Dip mit frischen Kräutern.",
      category: "Dips & Saucen",
    },
    {
      id: "scharf_sauce",
      name: "Scharfe Sauce",
      description: "Intensiv würzige Sauce für Liebhaber scharfer Aromen.",
      category: "Dips & Saucen",
    },
    {
      id: "knoblauch_sauce",
      name: "Knoblauch Sauce",
      description: "Aromatische Knoblauch Sauce mit Mayonnaise und frischen Kräutern.",
      category: "Dips & Saucen",
    },
    {
      id: "tahini_sauce",
      name: "Tahini Sauce",
      description: "Orientalische Spezialität",
      category: "Dips & Saucen",
      price: 4.0,
    },
    {
      id: "adzhika",
      name: "Adzhika",
      description: "Scharfe traditionelle Sauce",
      category: "Dips & Saucen",
      price: 3.5,
    },
    {
      id: "chimichurri",
      name: "Chimichurri",
      description: "Südamerikanische Würzsauce",
      category: "Dips & Saucen",
      price: 4.0,
    },
  ],
  desserts: [
    {
      id: "tiramisu",
      name: "Tiramisu",
      description: "Klassisches italienisches Tiramisu mit Mascarpone und Kakaopulver.",
      category: "Desserts",
    },
    {
      id: "baklava",
      name: "Baklava",
      description: "Knusprige Baklava mit Pistazien und aromatischem Honig.",
      category: "Desserts",
    },
    {
      id: "cheesecake",
      name: "Cheesecake",
      description: "Cremiger New York Cheesecake mit Himbeersauce.",
      category: "Desserts",
    },
    {
      id: "chocolate_cake",
      name: "Schokoladen Torte",
      description: "Saftige Schokoladen Torte mit cremiger Ganache.",
      category: "Desserts",
    },
    {
      id: "blini_eis",
      name: "Blini mit Eis",
      description: "Süße Pfannkuchen mit Vanilleeis",
      category: "Desserts",
      price: 9.5,
    },
    {
      id: "shemesh_tortenauswahl",
      name: "Hausgebackene Shemesh Tortenauswahl",
      description: "Vielfältige Auswahl an frisch gebackenen Torten",
      category: "Desserts",
      price: 9.5,
    },
    {
      id: "blini_marmelade",
      name: "Blinis mit Marmelade",
      description: "Mit hausgemachter Marmelade",
      category: "Desserts",
      price: 9.5,
    },
    {
      id: "wareniki_kirschen",
      name: "Wareniki mit Kirschen",
      description: "Mit süßem Schmand",
      category: "Desserts",
      price: 13.5,
    },
    {
      id: "suesse_birne",
      name: "Süße Birne mit Eis",
      description: "Köstliche Birnenvariante",
      category: "Desserts",
      price: 9.5,
    },
    {
      id: "fischsuppe",
      name: "Fischsuppe",
      description: "Klassische Fischsuppe",
      category: "Desserts",
      price: 16.9,
    },
    {
      id: "borscht",
      name: "Borscht",
      description: "Vegetarische Suppe aus Rote Beete und Kohl",
      category: "Desserts",
      price: 9.9,
    },
  ],
}

export function getPackageItems(packageName: "classic" | "gold" | "premium"): Record<string, number> {
  const limits = {
    classic: {
      vorspeisen: 2,
      hauptgaenge: 2,
      fingerfoods: 2,
      beilagen: 1,
      dips_saucen: 1,
      desserts: 1,
    },
    gold: {
      vorspeisen: 3,
      hauptgaenge: 3,
      fingerfoods: 3,
      beilagen: 2,
      dips_saucen: 2,
      desserts: 2,
    },
    premium: {
      vorspeisen: 4,
      hauptgaenge: 3,
      fingerfoods: 3,
      beilagen: 2,
      dips_saucen: 3,
      desserts: 3,
    },
  }

  return limits[packageName]
}
